# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: 1.0
# Stages can help you organize your steps in stages
stages:
  - clone
  - publish

steps:
  clone:
    title: Cloning repository
    type: git-clone
    repo: runeffective/spaceiq-eslint-preset
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: ${{CF_BRANCH}}
    git: spaceiqbot
    stage: clone

  publish:
    title: Publish package to GitHub registry
    image: ${{build}}
    stage: publish
    working_directory: /home/node
    when:
      branch:
        only:
          - main
    commands:
      - npm set //npm.pkg.github.com/:_authToken ${{GITHUB_TOKEN}}
      - rm -rf ./package.json
      - mv ./apps/web-marketplace/publish.json ./package.json
      - npm publish
